### ISSUE TITLE
dashboard produces no sound

### ISSUE THREAD

**Issue by pelikhan** [make4all/sonification#129]
- open dashboard
- connect microbit
- add note to sound level

```
DOMException: Failed to execute 'stop' on 'AudioScheduledSourceNode': cannot call stop without calling start first.
    at NoteSonify.stop (http://localhost:3000/static/js/main.chunk.js:3773:74)
    at Object.next (http://localhost:3000/static/js/main.chunk.js:3242:18)
    at http://localhost:3000/static/js/vendors~main.chunk.js:473564:71
    at OperatorSubscriber._this._next (http://localhost:3000/static/js/vendors~main.chunk.js:469748:9)
    at OperatorSubscriber.Subscriber.next (http://localhost:3000/static/js/vendors~main.chunk.js:467702:12)
    at http://localhost:3000/static/js/vendors~main.chunk.js:465857:31
    at notify_ (http://localhost:3000/static/js/vendors~main.chunk.js:465801:9)
    at Object.next (http://localhost:3000/static/js/vendors~main.chunk.js:465854:11)
    at Object.next (http://localhost:3000/static/js/vendors~main.chunk.js:465914:37)
    at Object.next (http://localhost:3000/static/js/vendors~main.chunk.js:467812:15)
    at SafeSubscriber.Subscriber._next (http://localhost:3000/static/js/vendors~main.chunk.js:467737:22)
    at SafeSubscriber.Subscriber.next (http://localhost:3000/static/js/vendors~main.chunk.js:467702:12)
    at http://localhost:3000/static/js/vendors~main.chunk.js:471161:68
    at OperatorSubscriber._this._next (http://localhost:3000/static/js/vendors~main.chunk.js:469748:9)
    at OperatorSubscriber.Subscriber.next (http://localhost:3000/static/js/vendors~main.chunk.js:467702:12)
    at http://localhost:3000/static/js/vendors~main.chunk.js:465857:31
    at notify_ (http://localhost:3000/static/js/vendors~main.chunk.js:465801:9)
    at Object.next (http://localhost:3000/static/js/vendors~main.chunk.js:465854:11)
    at Object.next (http://localhost:3000/static/js/vendors~main.chunk.js:465914:37)
    at Object.next (http://localhost:3000/static/js/vendors~main.chunk.js:467812:15)
    at SafeSubscriber.Subscriber._next (http://localhost:3000/static/js/vendors~main.chunk.js:467737:22)
    at SafeSubscriber.Subscriber.next (http://localhost:3000/static/js/vendors~main.chunk.js:467702:12)
    at http://localhost:3000/static/js/vendors~main.chunk.js:467480:22
    at errorContext (http://localhost:3000/static/js/vendors~main.chunk.js:476250:5)
    at NoteHandler.Subject.next (http://localhost:3000/static/js/vendors~main.chunk.js:467469:76)
    at Object.next (http://localhost:3000/static/js/vendors~main.chunk.js:460317:29)
    at Object.next (http://localhost:3000/static/js/vendors~main.chunk.js:467812:15)
    at SafeSubscriber.Subscriber._next (http://localhost:3000/static/js/vendors~main.chunk.js:467737:22)
    at SafeSubscriber.Subscriber.next (http://localhost:3000/static/js/vendors~main.chunk.js:467702:12)
    at http://localhost:3000/static/js/vendors~main.chunk.js:465857:31
    at notify_ (http://localhost:3000/static/js/vendors~main.chunk.js:465801:9)
    at Object.next (http://localhost:3000/static/js/vendors~main.chunk.js:465854:11)
    at Object.next (http://localhost:3000/static/js/vendors~main.chunk.js:465914:37)
    at Object.next (http://localhost:3000/static/js/vendors~main.chunk.js:467812:15)
    at SafeSubscriber.Subscriber._next (http://localhost:3000/static/js/vendors~main.chunk.js:467737:22)
    at SafeSubscriber.Subscriber.next (http://localhost:3000/static/js/vendors~main.chunk.js:467702:12)
    at http://localhost:3000/static/js/vendors~main.chunk.js:473565:18
    at OperatorSubscriber._this._next (http://localhost:3000/static/js/vendors~main.chunk.js:469748:9)
    at OperatorSubscriber.Subscriber.next (http://localhost:3000/static/js/vendors~main.chunk.js:467702:12)
    at http://localhost:3000/static/js/vendors~main.chunk.js:465857:31
    at notify_ (http://localhost:3000/static/js/vendors~main.chunk.js:465801:9)
    at Object.next (http://localhost:3000/static/js/vendors~main.chunk.js:465854:11)
    at Object.next (http://localhost:3000/static/js/vendors~main.chunk.js:465914:37)
    at Object.next (http://localhost:3000/static/js/vendors~main.chunk.js:467812:15)
    at SafeSubscriber.Subscriber._next (http://localhost:3000/static/js/vendors~main.chunk.js:467737:22)
    at SafeSubscriber.Subscriber.next (http://localhost:3000/static/js/vendors~main.chunk.js:467702:12)
    at http://localhost:3000/static/js/vendors~main.chunk.js:473565:18
    at OperatorSubscriber._this._next (http://localhost:3000/static/js/vendors~main.chunk.js:469748:9)
    at OperatorSubscriber.Subscriber.next (http://localhost:3000/static/js/vendors~main.chunk.js:467702:12)
    at http://localhost:3000/static/js/vendors~main.chunk.js:465857:31
```

**Comment by jrthompson33** [comment]
@pelikhan you have to press play to produce sound

The above error message should be captured in a try/catch - I don't think it breaks the UI, does it?

**Comment by venkateshpotluri** [comment]
> I had to scroll to see the play button

Screen reader users typically navigate web UIs by semantics i.e. by button, heading, etc. Play is marked up as a button, and the text above the play button is marked as heading level 3 (the second heading level 3 that a screen reader user, once familiar with the UI can get 2 in 2 key presses). Would this still be an issue?

> it wasn't obvious (no error message) that it should be pressed.

Were you expecting to see the error in a particular part of the UI, after you performed some action? or were you referring to the console error? We walk the participants through the UI and some of the handlers with a potentiometer before we ask them to perform tasks and we demonstrate the play button at this point.

**Comment by pelikhan** [comment]
Closing this as play fixes this issue.
